// ISC License (ISC)
//
// Copyright (c) 2016, Zeyla Hellyer <zeylahellyer@gmail.com>
//
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
//
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER
// RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
// CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
// CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
//
// What is ISO 3166-1?
//
// | ISO 3166-1 is part of the ISO 3166 standard published by the International
// | Organization for Standardization (ISO), and defines codes for the names of
// | countries, dependent territories, and special areas of geographical
// | interest.
// |
// | - [Wikipedia](http://en.wikipedia.org/wiki/ISO_3166-1)
//
// Originally by zeyla on GitHub.

use CountryCode;

pub const ALL: [CountryCode; 249] = [
    // Begin
    CountryCode {
        alpha2: "AF",
        alpha3: "AFG",
        name: "Afghanistan",
        num: "004",
    },
    CountryCode {
        alpha2: "AL",
        alpha3: "ALB",
        name: "Albania",
        num: "008",
    },
    CountryCode {
        alpha2: "AQ",
        alpha3: "ATA",
        name: "Antarctica",
        num: "010",
    },
    CountryCode {
        alpha2: "DZ",
        alpha3: "DZA",
        name: "Algeria",
        num: "012",
    },
    CountryCode {
        alpha2: "AS",
        alpha3: "ASM",
        name: "American Samoa",
        num: "016",
    },
    CountryCode {
        alpha2: "AD",
        alpha3: "AND",
        name: "Andorra",
        num: "020",
    },
    CountryCode {
        alpha2: "AO",
        alpha3: "AGO",
        name: "Angola",
        num: "024",
    },
    CountryCode {
        alpha2: "AG",
        alpha3: "ATG",
        name: "Antigua and Barbuda",
        num: "028",
    },
    CountryCode {
        alpha2: "AZ",
        alpha3: "AZE",
        name: "Azerbaijan",
        num: "031",
    },
    CountryCode {
        alpha2: "AR",
        alpha3: "ARG",
        name: "Argentina",
        num: "032",
    },
    CountryCode {
        alpha2: "AU",
        alpha3: "AUS",
        name: "Australia",
        num: "036",
    },
    CountryCode {
        alpha2: "AT",
        alpha3: "AUT",
        name: "Austria",
        num: "040",
    },
    CountryCode {
        alpha2: "BS",
        alpha3: "BHS",
        name: "Bahamas",
        num: "044",
    },
    CountryCode {
        alpha2: "BH",
        alpha3: "BHR",
        name: "Bahrain",
        num: "048",
    },
    CountryCode {
        alpha2: "BD",
        alpha3: "BGD",
        name: "Bangladesh",
        num: "050",
    },
    CountryCode {
        alpha2: "AM",
        alpha3: "ARM",
        name: "Armenia",
        num: "051",
    },
    CountryCode {
        alpha2: "BB",
        alpha3: "BRB",
        name: "Barbados",
        num: "052",
    },
    CountryCode {
        alpha2: "BE",
        alpha3: "BEL",
        name: "Belgium",
        num: "056",
    },
    CountryCode {
        alpha2: "BM",
        alpha3: "BMU",
        name: "Bermuda",
        num: "060",
    },
    CountryCode {
        alpha2: "BT",
        alpha3: "BTN",
        name: "Bhutan",
        num: "064",
    },
    CountryCode {
        alpha2: "BO",
        alpha3: "BOL",
        name: "Bolivia (Plurinational State of)",
        num: "068",
    },
    CountryCode {
        alpha2: "BA",
        alpha3: "BIH",
        name: "Bosnia and Herzegovina",
        num: "070",
    },
    CountryCode {
        alpha2: "BW",
        alpha3: "BWA",
        name: "Botswana",
        num: "072",
    },
    CountryCode {
        alpha2: "BV",
        alpha3: "BVT",
        name: "Bouvet Island",
        num: "074",
    },
    CountryCode {
        alpha2: "BR",
        alpha3: "BRA",
        name: "Brazil",
        num: "076",
    },
    CountryCode {
        alpha2: "BZ",
        alpha3: "BLZ",
        name: "Belize",
        num: "084",
    },
    CountryCode {
        alpha2: "IO",
        alpha3: "IOT",
        name: "British Indian Ocean Territory",
        num: "086",
    },
    CountryCode {
        alpha2: "SB",
        alpha3: "SLB",
        name: "Solomon Islands",
        num: "090",
    },
    CountryCode {
        alpha2: "VG",
        alpha3: "VGB",
        name: "Virgin Islands (British)",
        num: "092",
    },
    CountryCode {
        alpha2: "BN",
        alpha3: "BRN",
        name: "Brunei Darussalam",
        num: "096",
    },
    CountryCode {
        alpha2: "BG",
        alpha3: "BGR",
        name: "Bulgaria",
        num: "100",
    },
    CountryCode {
        alpha2: "MM",
        alpha3: "MMR",
        name: "Myanmar",
        num: "104",
    },
    CountryCode {
        alpha2: "BI",
        alpha3: "BDI",
        name: "Burundi",
        num: "108",
    },
    CountryCode {
        alpha2: "BY",
        alpha3: "BLR",
        name: "Belarus",
        num: "112",
    },
    CountryCode {
        alpha2: "KH",
        alpha3: "KHM",
        name: "Cambodia",
        num: "116",
    },
    CountryCode {
        alpha2: "CM",
        alpha3: "CMR",
        name: "Cameroon",
        num: "120",
    },
    CountryCode {
        alpha2: "CA",
        alpha3: "CAN",
        name: "Canada",
        num: "124",
    },
    CountryCode {
        alpha2: "CV",
        alpha3: "CPV",
        name: "Cabo Verde",
        num: "132",
    },
    CountryCode {
        alpha2: "KY",
        alpha3: "CYM",
        name: "Cayman Islands",
        num: "136",
    },
    CountryCode {
        alpha2: "CF",
        alpha3: "CAF",
        name: "Central African Republic",
        num: "140",
    },
    CountryCode {
        alpha2: "LK",
        alpha3: "LKA",
        name: "Sri Lanka",
        num: "144",
    },
    CountryCode {
        alpha2: "TD",
        alpha3: "TCD",
        name: "Chad",
        num: "148",
    },
    CountryCode {
        alpha2: "CL",
        alpha3: "CHL",
        name: "Chile",
        num: "152",
    },
    CountryCode {
        alpha2: "CN",
        alpha3: "CHN",
        name: "China",
        num: "156",
    },
    CountryCode {
        alpha2: "TW",
        alpha3: "TWN",
        name: "Taiwan, Province of China[a]",
        num: "158",
    },
    CountryCode {
        alpha2: "CX",
        alpha3: "CXR",
        name: "Christmas Island",
        num: "162",
    },
    CountryCode {
        alpha2: "CC",
        alpha3: "CCK",
        name: "Cocos (Keeling) Islands",
        num: "166",
    },
    CountryCode {
        alpha2: "CO",
        alpha3: "COL",
        name: "Colombia",
        num: "170",
    },
    CountryCode {
        alpha2: "KM",
        alpha3: "COM",
        name: "Comoros",
        num: "174",
    },
    CountryCode {
        alpha2: "YT",
        alpha3: "MYT",
        name: "Mayotte",
        num: "175",
    },
    CountryCode {
        alpha2: "CG",
        alpha3: "COG",
        name: "Congo",
        num: "178",
    },
    CountryCode {
        alpha2: "CD",
        alpha3: "COD",
        name: "Congo (Democratic Republic of the)",
        num: "180",
    },
    CountryCode {
        alpha2: "CK",
        alpha3: "COK",
        name: "Cook Islands",
        num: "184",
    },
    CountryCode {
        alpha2: "CR",
        alpha3: "CRI",
        name: "Costa Rica",
        num: "188",
    },
    CountryCode {
        alpha2: "HR",
        alpha3: "HRV",
        name: "Croatia",
        num: "191",
    },
    CountryCode {
        alpha2: "CU",
        alpha3: "CUB",
        name: "Cuba",
        num: "192",
    },
    CountryCode {
        alpha2: "CY",
        alpha3: "CYP",
        name: "Cyprus",
        num: "196",
    },
    CountryCode {
        alpha2: "CZ",
        alpha3: "CZE",
        name: "Czech Republic",
        num: "203",
    },
    CountryCode {
        alpha2: "BJ",
        alpha3: "BEN",
        name: "Benin",
        num: "204",
    },
    CountryCode {
        alpha2: "DK",
        alpha3: "DNK",
        name: "Denmark",
        num: "208",
    },
    CountryCode {
        alpha2: "DM",
        alpha3: "DMA",
        name: "Dominica",
        num: "212",
    },
    CountryCode {
        alpha2: "DO",
        alpha3: "DOM",
        name: "Dominican Republic",
        num: "214",
    },
    CountryCode {
        alpha2: "EC",
        alpha3: "ECU",
        name: "Ecuador",
        num: "218",
    },
    CountryCode {
        alpha2: "SV",
        alpha3: "SLV",
        name: "El Salvador",
        num: "222",
    },
    CountryCode {
        alpha2: "GQ",
        alpha3: "GNQ",
        name: "Equatorial Guinea",
        num: "226",
    },
    CountryCode {
        alpha2: "ET",
        alpha3: "ETH",
        name: "Ethiopia",
        num: "231",
    },
    CountryCode {
        alpha2: "ER",
        alpha3: "ERI",
        name: "Eritrea",
        num: "232",
    },
    CountryCode {
        alpha2: "EE",
        alpha3: "EST",
        name: "Estonia",
        num: "233",
    },
    CountryCode {
        alpha2: "FO",
        alpha3: "FRO",
        name: "Faroe Islands",
        num: "234",
    },
    CountryCode {
        alpha2: "FK",
        alpha3: "FLK",
        name: "Falkland Islands",
        num: "238",
    },
    CountryCode {
        alpha2: "GS",
        alpha3: "SGS",
        name: "South Georgia and the South Sandwich Islands",
        num: "239",
    },
    CountryCode {
        alpha2: "FJ",
        alpha3: "FJI",
        name: "Fiji",
        num: "242",
    },
    CountryCode {
        alpha2: "FI",
        alpha3: "FIN",
        name: "Finland",
        num: "246",
    },
    CountryCode {
        alpha2: "AX",
        alpha3: "ALA",
        name: "Åland Islands",
        num: "248",
    },
    CountryCode {
        alpha2: "FR",
        alpha3: "FRA",
        name: "France",
        num: "250",
    },
    CountryCode {
        alpha2: "GF",
        alpha3: "GUF",
        name: "French Guiana",
        num: "254",
    },
    CountryCode {
        alpha2: "PF",
        alpha3: "PYF",
        name: "French Polynesia",
        num: "258",
    },
    CountryCode {
        alpha2: "TF",
        alpha3: "ATF",
        name: "French Southern Territories",
        num: "260",
    },
    CountryCode {
        alpha2: "DJ",
        alpha3: "DJI",
        name: "Djibouti",
        num: "262",
    },
    CountryCode {
        alpha2: "GA",
        alpha3: "GAB",
        name: "Gabon",
        num: "266",
    },
    CountryCode {
        alpha2: "GE",
        alpha3: "GEO",
        name: "Georgia",
        num: "268",
    },
    CountryCode {
        alpha2: "GM",
        alpha3: "GMB",
        name: "Gambia",
        num: "270",
    },
    CountryCode {
        alpha2: "PS",
        alpha3: "PSE",
        name: "Palestine, State of",
        num: "275",
    },
    CountryCode {
        alpha2: "DE",
        alpha3: "DEU",
        name: "Germany",
        num: "276",
    },
    CountryCode {
        alpha2: "GH",
        alpha3: "GHA",
        name: "Ghana",
        num: "288",
    },
    CountryCode {
        alpha2: "GI",
        alpha3: "GIB",
        name: "Gibraltar",
        num: "292",
    },
    CountryCode {
        alpha2: "KI",
        alpha3: "KIR",
        name: "Kiribati",
        num: "296",
    },
    CountryCode {
        alpha2: "GR",
        alpha3: "GRC",
        name: "Greece",
        num: "300",
    },
    CountryCode {
        alpha2: "GL",
        alpha3: "GRL",
        name: "Greenland",
        num: "304",
    },
    CountryCode {
        alpha2: "GD",
        alpha3: "GRD",
        name: "Grenada",
        num: "308",
    },
    CountryCode {
        alpha2: "GP",
        alpha3: "GLP",
        name: "Guadeloupe",
        num: "312",
    },
    CountryCode {
        alpha2: "GU",
        alpha3: "GUM",
        name: "Guam",
        num: "316",
    },
    CountryCode {
        alpha2: "GT",
        alpha3: "GTM",
        name: "Guatemala",
        num: "320",
    },
    CountryCode {
        alpha2: "GN",
        alpha3: "GIN",
        name: "Guinea",
        num: "324",
    },
    CountryCode {
        alpha2: "GY",
        alpha3: "GUY",
        name: "Guyana",
        num: "328",
    },
    CountryCode {
        alpha2: "HT",
        alpha3: "HTI",
        name: "Haiti",
        num: "332",
    },
    CountryCode {
        alpha2: "HM",
        alpha3: "HMD",
        name: "Heard Island and McDonald Islands",
        num: "334",
    },
    CountryCode {
        alpha2: "VA",
        alpha3: "VAT",
        name: "Holy See",
        num: "336",
    },
    CountryCode {
        alpha2: "HN",
        alpha3: "HND",
        name: "Honduras",
        num: "340",
    },
    CountryCode {
        alpha2: "HK",
        alpha3: "HKG",
        name: "Hong Kong",
        num: "344",
    },
    CountryCode {
        alpha2: "HU",
        alpha3: "HUN",
        name: "Hungary",
        num: "348",
    },
    CountryCode {
        alpha2: "IS",
        alpha3: "ISL",
        name: "Iceland",
        num: "352",
    },
    CountryCode {
        alpha2: "IN",
        alpha3: "IND",
        name: "India",
        num: "356",
    },
    CountryCode {
        alpha2: "ID",
        alpha3: "IDN",
        name: "Indonesia",
        num: "360",
    },
    CountryCode {
        alpha2: "IR",
        alpha3: "IRN",
        name: "Iran (Islamic Republic of)",
        num: "364",
    },
    CountryCode {
        alpha2: "IQ",
        alpha3: "IRQ",
        name: "Iraq",
        num: "368",
    },
    CountryCode {
        alpha2: "IE",
        alpha3: "IRL",
        name: "Ireland",
        num: "372",
    },
    CountryCode {
        alpha2: "IL",
        alpha3: "ISR",
        name: "Israel",
        num: "376",
    },
    CountryCode {
        alpha2: "IT",
        alpha3: "ITA",
        name: "Italy",
        num: "380",
    },
    CountryCode {
        alpha2: "CI",
        alpha3: "CIV",
        name: "Côte d'Ivoire",
        num: "384",
    },
    CountryCode {
        alpha2: "JM",
        alpha3: "JAM",
        name: "Jamaica",
        num: "388",
    },
    CountryCode {
        alpha2: "JP",
        alpha3: "JPN",
        name: "Japan",
        num: "392",
    },
    CountryCode {
        alpha2: "KZ",
        alpha3: "KAZ",
        name: "Kazakhstan",
        num: "398",
    },
    CountryCode {
        alpha2: "JO",
        alpha3: "JOR",
        name: "Jordan",
        num: "400",
    },
    CountryCode {
        alpha2: "KE",
        alpha3: "KEN",
        name: "Kenya",
        num: "404",
    },
    CountryCode {
        alpha2: "KP",
        alpha3: "PRK",
        name: "Korea (Democratic People's Republic of)",
        num: "408",
    },
    CountryCode {
        alpha2: "KR",
        alpha3: "KOR",
        name: "Korea (Republic of)",
        num: "410",
    },
    CountryCode {
        alpha2: "KW",
        alpha3: "KWT",
        name: "Kuwait",
        num: "414",
    },
    CountryCode {
        alpha2: "KG",
        alpha3: "KGZ",
        name: "Kyrgyzstan",
        num: "417",
    },
    CountryCode {
        alpha2: "LA",
        alpha3: "LAO",
        name: "Lao People's Democratic Republic",
        num: "418",
    },
    CountryCode {
        alpha2: "LB",
        alpha3: "LBN",
        name: "Lebanon",
        num: "422",
    },
    CountryCode {
        alpha2: "LS",
        alpha3: "LSO",
        name: "Lesotho",
        num: "426",
    },
    CountryCode {
        alpha2: "LV",
        alpha3: "LVA",
        name: "Latvia",
        num: "428",
    },
    CountryCode {
        alpha2: "LR",
        alpha3: "LBR",
        name: "Liberia",
        num: "430",
    },
    CountryCode {
        alpha2: "LY",
        alpha3: "LBY",
        name: "Libya",
        num: "434",
    },
    CountryCode {
        alpha2: "LI",
        alpha3: "LIE",
        name: "Liechtenstein",
        num: "438",
    },
    CountryCode {
        alpha2: "LT",
        alpha3: "LTU",
        name: "Lithuania",
        num: "440",
    },
    CountryCode {
        alpha2: "LU",
        alpha3: "LUX",
        name: "Luxembourg",
        num: "442",
    },
    CountryCode {
        alpha2: "MO",
        alpha3: "MAC",
        name: "Macao",
        num: "446",
    },
    CountryCode {
        alpha2: "MG",
        alpha3: "MDG",
        name: "Madagascar",
        num: "450",
    },
    CountryCode {
        alpha2: "MW",
        alpha3: "MWI",
        name: "Malawi",
        num: "454",
    },
    CountryCode {
        alpha2: "MY",
        alpha3: "MYS",
        name: "Malaysia",
        num: "458",
    },
    CountryCode {
        alpha2: "MV",
        alpha3: "MDV",
        name: "Maldives",
        num: "462",
    },
    CountryCode {
        alpha2: "ML",
        alpha3: "MLI",
        name: "Mali",
        num: "466",
    },
    CountryCode {
        alpha2: "MT",
        alpha3: "MLT",
        name: "Malta",
        num: "470",
    },
    CountryCode {
        alpha2: "MQ",
        alpha3: "MTQ",
        name: "Martinique",
        num: "474",
    },
    CountryCode {
        alpha2: "MR",
        alpha3: "MRT",
        name: "Mauritania",
        num: "478",
    },
    CountryCode {
        alpha2: "MU",
        alpha3: "MUS",
        name: "Mauritius",
        num: "480",
    },
    CountryCode {
        alpha2: "MX",
        alpha3: "MEX",
        name: "Mexico",
        num: "484",
    },
    CountryCode {
        alpha2: "MC",
        alpha3: "MCO",
        name: "Monaco",
        num: "492",
    },
    CountryCode {
        alpha2: "MN",
        alpha3: "MNG",
        name: "Mongolia",
        num: "496",
    },
    CountryCode {
        alpha2: "MD",
        alpha3: "MDA",
        name: "Moldova (Republic of)",
        num: "498",
    },
    CountryCode {
        alpha2: "ME",
        alpha3: "MNE",
        name: "Montenegro",
        num: "499",
    },
    CountryCode {
        alpha2: "MS",
        alpha3: "MSR",
        name: "Montserrat",
        num: "500",
    },
    CountryCode {
        alpha2: "MA",
        alpha3: "MAR",
        name: "Morocco",
        num: "504",
    },
    CountryCode {
        alpha2: "MZ",
        alpha3: "MOZ",
        name: "Mozambique",
        num: "508",
    },
    CountryCode {
        alpha2: "OM",
        alpha3: "OMN",
        name: "Oman",
        num: "512",
    },
    CountryCode {
        alpha2: "NA",
        alpha3: "NAM",
        name: "Namibia",
        num: "516",
    },
    CountryCode {
        alpha2: "NR",
        alpha3: "NRU",
        name: "Nauru",
        num: "520",
    },
    CountryCode {
        alpha2: "NP",
        alpha3: "NPL",
        name: "Nepal",
        num: "524",
    },
    CountryCode {
        alpha2: "NL",
        alpha3: "NLD",
        name: "Netherlands",
        num: "528",
    },
    CountryCode {
        alpha2: "CW",
        alpha3: "CUW",
        name: "Curaçao",
        num: "531",
    },
    CountryCode {
        alpha2: "AW",
        alpha3: "ABW",
        name: "Aruba",
        num: "533",
    },
    CountryCode {
        alpha2: "SX",
        alpha3: "SXM",
        name: "Sint Maarten (Dutch part)",
        num: "534",
    },
    CountryCode {
        alpha2: "BQ",
        alpha3: "BES",
        name: "Bonaire, Sint Eustatius and Saba",
        num: "535",
    },
    CountryCode {
        alpha2: "NC",
        alpha3: "NCL",
        name: "New Caledonia",
        num: "540",
    },
    CountryCode {
        alpha2: "VU",
        alpha3: "VUT",
        name: "Vanuatu",
        num: "548",
    },
    CountryCode {
        alpha2: "NZ",
        alpha3: "NZL",
        name: "New Zealand",
        num: "554",
    },
    CountryCode {
        alpha2: "NI",
        alpha3: "NIC",
        name: "Nicaragua",
        num: "558",
    },
    CountryCode {
        alpha2: "NE",
        alpha3: "NER",
        name: "Niger",
        num: "562",
    },
    CountryCode {
        alpha2: "NG",
        alpha3: "NGA",
        name: "Nigeria",
        num: "566",
    },
    CountryCode {
        alpha2: "NU",
        alpha3: "NIU",
        name: "Niue",
        num: "570",
    },
    CountryCode {
        alpha2: "NF",
        alpha3: "NFK",
        name: "Norfolk Island",
        num: "574",
    },
    CountryCode {
        alpha2: "NO",
        alpha3: "NOR",
        name: "Norway",
        num: "578",
    },
    CountryCode {
        alpha2: "MP",
        alpha3: "MNP",
        name: "Northern Mariana Islands",
        num: "580",
    },
    CountryCode {
        alpha2: "UM",
        alpha3: "UMI",
        name: "United States Minor Outlying Islands",
        num: "581",
    },
    CountryCode {
        alpha2: "FM",
        alpha3: "FSM",
        name: "Micronesia (Federated States of)",
        num: "583",
    },
    CountryCode {
        alpha2: "MH",
        alpha3: "MHL",
        name: "Marshall Islands",
        num: "584",
    },
    CountryCode {
        alpha2: "PW",
        alpha3: "PLW",
        name: "Palau",
        num: "585",
    },
    CountryCode {
        alpha2: "PK",
        alpha3: "PAK",
        name: "Pakistan",
        num: "586",
    },
    CountryCode {
        alpha2: "PA",
        alpha3: "PAN",
        name: "Panama",
        num: "591",
    },
    CountryCode {
        alpha2: "PG",
        alpha3: "PNG",
        name: "Papua New Guinea",
        num: "598",
    },
    CountryCode {
        alpha2: "PY",
        alpha3: "PRY",
        name: "Paraguay",
        num: "600",
    },
    CountryCode {
        alpha2: "PE",
        alpha3: "PER",
        name: "Peru",
        num: "604",
    },
    CountryCode {
        alpha2: "PH",
        alpha3: "PHL",
        name: "Philippines",
        num: "608",
    },
    CountryCode {
        alpha2: "PN",
        alpha3: "PCN",
        name: "Pitcairn",
        num: "612",
    },
    CountryCode {
        alpha2: "PL",
        alpha3: "POL",
        name: "Poland",
        num: "616",
    },
    CountryCode {
        alpha2: "PT",
        alpha3: "PRT",
        name: "Portugal",
        num: "620",
    },
    CountryCode {
        alpha2: "GW",
        alpha3: "GNB",
        name: "Guinea-Bissau",
        num: "624",
    },
    CountryCode {
        alpha2: "TL",
        alpha3: "TLS",
        name: "Timor-Leste",
        num: "626",
    },
    CountryCode {
        alpha2: "PR",
        alpha3: "PRI",
        name: "Puerto Rico",
        num: "630",
    },
    CountryCode {
        alpha2: "QA",
        alpha3: "QAT",
        name: "Qatar",
        num: "634",
    },
    CountryCode {
        alpha2: "RE",
        alpha3: "REU",
        name: "Réunion",
        num: "638",
    },
    CountryCode {
        alpha2: "RO",
        alpha3: "ROU",
        name: "Romania",
        num: "642",
    },
    CountryCode {
        alpha2: "RU",
        alpha3: "RUS",
        name: "Russian Federation",
        num: "643",
    },
    CountryCode {
        alpha2: "RW",
        alpha3: "RWA",
        name: "Rwanda",
        num: "646",
    },
    CountryCode {
        alpha2: "BL",
        alpha3: "BLM",
        name: "Saint Barthélemy",
        num: "652",
    },
    CountryCode {
        alpha2: "SH",
        alpha3: "SHN",
        name: "Saint Helena, Ascension and Tristan da Cunha",
        num: "654",
    },
    CountryCode {
        alpha2: "KN",
        alpha3: "KNA",
        name: "Saint Kitts and Nevis",
        num: "659",
    },
    CountryCode {
        alpha2: "AI",
        alpha3: "AIA",
        name: "Anguilla",
        num: "660",
    },
    CountryCode {
        alpha2: "LC",
        alpha3: "LCA",
        name: "Saint Lucia",
        num: "662",
    },
    CountryCode {
        alpha2: "MF",
        alpha3: "MAF",
        name: "Saint Martin (French part)",
        num: "663",
    },
    CountryCode {
        alpha2: "PM",
        alpha3: "SPM",
        name: "Saint Pierre and Miquelon",
        num: "666",
    },
    CountryCode {
        alpha2: "VC",
        alpha3: "VCT",
        name: "Saint Vincent and the Grenadines",
        num: "670",
    },
    CountryCode {
        alpha2: "SM",
        alpha3: "SMR",
        name: "San Marino",
        num: "674",
    },
    CountryCode {
        alpha2: "ST",
        alpha3: "STP",
        name: "Sao Tome and Principe",
        num: "678",
    },
    CountryCode {
        alpha2: "SA",
        alpha3: "SAU",
        name: "Saudi Arabia",
        num: "682",
    },
    CountryCode {
        alpha2: "SN",
        alpha3: "SEN",
        name: "Senegal",
        num: "686",
    },
    CountryCode {
        alpha2: "RS",
        alpha3: "SRB",
        name: "Serbia",
        num: "688",
    },
    CountryCode {
        alpha2: "SC",
        alpha3: "SYC",
        name: "Seychelles",
        num: "690",
    },
    CountryCode {
        alpha2: "SL",
        alpha3: "SLE",
        name: "Sierra Leone",
        num: "694",
    },
    CountryCode {
        alpha2: "SG",
        alpha3: "SGP",
        name: "Singapore",
        num: "702",
    },
    CountryCode {
        alpha2: "SK",
        alpha3: "SVK",
        name: "Slovakia",
        num: "703",
    },
    CountryCode {
        alpha2: "VN",
        alpha3: "VNM",
        name: "Viet Nam",
        num: "704",
    },
    CountryCode {
        alpha2: "SI",
        alpha3: "SVN",
        name: "Slovenia",
        num: "705",
    },
    CountryCode {
        alpha2: "SO",
        alpha3: "SOM",
        name: "Somalia",
        num: "706",
    },
    CountryCode {
        alpha2: "ZA",
        alpha3: "ZAF",
        name: "South Africa",
        num: "710",
    },
    CountryCode {
        alpha2: "ZW",
        alpha3: "ZWE",
        name: "Zimbabwe",
        num: "716",
    },
    CountryCode {
        alpha2: "ES",
        alpha3: "ESP",
        name: "Spain",
        num: "724",
    },
    CountryCode {
        alpha2: "SS",
        alpha3: "SSD",
        name: "South Sudan",
        num: "728",
    },
    CountryCode {
        alpha2: "SD",
        alpha3: "SDN",
        name: "Sudan",
        num: "729",
    },
    CountryCode {
        alpha2: "EH",
        alpha3: "ESH",
        name: "Western Sahara",
        num: "732",
    },
    CountryCode {
        alpha2: "SR",
        alpha3: "SUR",
        name: "Suriname",
        num: "740",
    },
    CountryCode {
        alpha2: "SJ",
        alpha3: "SJM",
        name: "Svalbard and Jan Mayen",
        num: "744",
    },
    CountryCode {
        alpha2: "SZ",
        alpha3: "SWZ",
        name: "Swaziland",
        num: "748",
    },
    CountryCode {
        alpha2: "SE",
        alpha3: "SWE",
        name: "Sweden",
        num: "752",
    },
    CountryCode {
        alpha2: "CH",
        alpha3: "CHE",
        name: "Switzerland",
        num: "756",
    },
    CountryCode {
        alpha2: "SY",
        alpha3: "SYR",
        name: "Syrian Arab Republic",
        num: "760",
    },
    CountryCode {
        alpha2: "TJ",
        alpha3: "TJK",
        name: "Tajikistan",
        num: "762",
    },
    CountryCode {
        alpha2: "TH",
        alpha3: "THA",
        name: "Thailand",
        num: "764",
    },
    CountryCode {
        alpha2: "TG",
        alpha3: "TGO",
        name: "Togo",
        num: "768",
    },
    CountryCode {
        alpha2: "TK",
        alpha3: "TKL",
        name: "Tokelau",
        num: "772",
    },
    CountryCode {
        alpha2: "TO",
        alpha3: "TON",
        name: "Tonga",
        num: "776",
    },
    CountryCode {
        alpha2: "TT",
        alpha3: "TTO",
        name: "Trinidad and Tobago",
        num: "780",
    },
    CountryCode {
        alpha2: "AE",
        alpha3: "ARE",
        name: "United Arab Emirates",
        num: "784",
    },
    CountryCode {
        alpha2: "TN",
        alpha3: "TUN",
        name: "Tunisia",
        num: "788",
    },
    CountryCode {
        alpha2: "TR",
        alpha3: "TUR",
        name: "Turkey",
        num: "792",
    },
    CountryCode {
        alpha2: "TM",
        alpha3: "TKM",
        name: "Turkmenistan",
        num: "795",
    },
    CountryCode {
        alpha2: "TC",
        alpha3: "TCA",
        name: "Turks and Caicos Islands",
        num: "796",
    },
    CountryCode {
        alpha2: "TV",
        alpha3: "TUV",
        name: "Tuvalu",
        num: "798",
    },
    CountryCode {
        alpha2: "UG",
        alpha3: "UGA",
        name: "Uganda",
        num: "800",
    },
    CountryCode {
        alpha2: "UA",
        alpha3: "UKR",
        name: "Ukraine",
        num: "804",
    },
    CountryCode {
        alpha2: "MK",
        alpha3: "MKD",
        name: "Macedonia (the former Yugoslav Republic of)",
        num: "807",
    },
    CountryCode {
        alpha2: "EG",
        alpha3: "EGY",
        name: "Egypt",
        num: "818",
    },
    CountryCode {
        alpha2: "GB",
        alpha3: "GBR",
        name: "United Kingdom of Great Britain and Northern Ireland",
        num: "826",
    },
    CountryCode {
        alpha2: "GG",
        alpha3: "GGY",
        name: "Guernsey",
        num: "831",
    },
    CountryCode {
        alpha2: "JE",
        alpha3: "JEY",
        name: "Jersey",
        num: "832",
    },
    CountryCode {
        alpha2: "IM",
        alpha3: "IMN",
        name: "Isle of Man",
        num: "833",
    },
    CountryCode {
        alpha2: "TZ",
        alpha3: "TZA",
        name: "Tanzania, United Republic of",
        num: "834",
    },
    CountryCode {
        alpha2: "US",
        alpha3: "USA",
        name: "United States of America",
        num: "840",
    },
    CountryCode {
        alpha2: "VI",
        alpha3: "VIR",
        name: "Virgin Islands (U.S.)",
        num: "850",
    },
    CountryCode {
        alpha2: "BF",
        alpha3: "BFA",
        name: "Burkina Faso",
        num: "854",
    },
    CountryCode {
        alpha2: "UY",
        alpha3: "URY",
        name: "Uruguay",
        num: "858",
    },
    CountryCode {
        alpha2: "UZ",
        alpha3: "UZB",
        name: "Uzbekistan",
        num: "860",
    },
    CountryCode {
        alpha2: "VE",
        alpha3: "VEN",
        name: "Venezuela (Bolivarian Republic of)",
        num: "862",
    },
    CountryCode {
        alpha2: "WF",
        alpha3: "WLF",
        name: "Wallis and Futuna",
        num: "876",
    },
    CountryCode {
        alpha2: "WS",
        alpha3: "WSM",
        name: "Samoa",
        num: "882",
    },
    CountryCode {
        alpha2: "YE",
        alpha3: "YEM",
        name: "Yemen",
        num: "887",
    },
    CountryCode {
        alpha2: "ZM",
        alpha3: "ZMB",
        name: "Zambia",
        num: "894",
    },
    // End
];

/// Returns all `CountryCode`s defined by ISO 3166-1.
///
/// # Examples
///
/// ```rust
/// let countries = iso3166_1::all();
/// ```
// A function that returns a reference to a really big array of all the country
// codes designated by ISO 3166-1.
//
// These can be automatically updated by running 'make update'.
//
// The 'Begin' and 'End' comments are essential as it tells the update script
// where to begin and end inserting the country codes.
//
// Source:
// https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements
pub fn all() -> &'static [CountryCode] {
    &ALL
}
